## Essential To Start

### Load Data

In [162]:
import pandas as pd
'''
    Two Things: DataFrames and Series
        --> DataFrames: Two Dimentionnal (Row/Column) = 2D data structure
'''

# Load DataFrame
orders_dataframe = pd.read_csv("./orders.csv")
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Country': ['USA', 'Canada', 'UK']
}
df = pd.DataFrame(data)
print(df)

      Name  Age Country
0    Alice   25     USA
1      Bob   30  Canada
2  Charlie   35      UK

### Util FUnctions

In [163]:
# DataFrame FUnctions
orders_dataframe.head() # first 5 rows
orders_dataframe.tail() # last 5 rows
orders_dataframe.describe()
print(list(orders_dataframe.columns))
orders_dataframe.index # indices for each row

['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price', 'OrderDate', 'Shipped', 'Country']

RangeIndex(start=0, stop=40, step=1)

### Filtering Data

In [159]:
# Access To Columns & Filtering Data
orders_dataframe["Country"].head()
orders_dataframe[orders_dataframe['Country'] == 'USA']
orders_dataframe[[(True if i % 2  == 1 else False) for i in range (0, 40)]]
orders_dataframe["CustomerName"].isin(["Ahmed", "Mohammed"])
orders_dataframe[orders_dataframe["Country"].str.startswith("M")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco

### CRUD Operations in Pandas

In [ ]:
import copy
copy_orders_dataframe = copy.deepcopy(orders_dataframe)
copy_orders_dataframe

# Display Row (.loc and .lloc)
# df.iloc[row_indexer, column_indexer], df.loc[row_indexer, column_indexer]
copy_orders_dataframe.iloc[0:4] # get rows from 0 to 4
copy_orders_dataframe.loc[0:3, "Production_cost"] # get rows from zero to 3 from column Production_cost

# TO use label in .loc we need to set index for dataframe
# copy_orders_dataframe = copy_orders_dataframe.set_index("OrderID")
# copy_orders_dataframe.loc[1003].head()
print(copy_orders_dataframe.index)
copy_orders_dataframe.iloc[0]

# reset index and keep old by creating new collumn
copy_orders_dataframe = copy_orders_dataframe.reset_index(drop=False)

In [ ]:
# Insert Rows
new_row = pd.DataFrame([{"OrderID": 1041, "CustomerName": "Abdellah", "Product": "Printer Paper", "Category": "Stationery", "Quantity": 20, "Price": 8.0, "OrderDate": "2026-06-17", "Shipped": "Yes", "Country": "Morocco"}])

new_copy_orders_dataframe = pd.concat([copy_orders_dataframe, new_row], ignore_index=True)
new_copy_orders_dataframe

In [ ]:
# Update (Modify Values)
# get country column
new_copy_orders_dataframe.loc[new_copy_orders_dataframe["CustomerName"] == "Abdellah", "Country"] = 100
new_copy_orders_dataframe.tail(1)

# Update All OrderID by 1000
new_copy_orders_dataframe.loc[[True for i in range(0, 41)], "OrderID"] = 1000
new_copy_orders_dataframe

In [180]:
# Delete (Drop Data)
# axis = 0 --> means row && axis = 1 --> mean column
new_copy_orders_dataframe1 = new_copy_orders_dataframe.drop(2, axis=0) # delete element 2 on rows
new_copy_orders_dataframe1
new_copy_orders_dataframe2 = new_copy_orders_dataframe1.drop("OrderID", axis=1) # Delete OrderID
new_copy_orders_dataframe2

new_copy_orders_dataframe3 = new_copy_orders_dataframe2[new_copy_orders_dataframe1["CustomerName"] == "Abdellah"] # drop all rows
new_copy_orders_dataframe3

,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
40,Abdellah,Printer Paper,Stationery,20,8.0,2026-06-17,Yes,100

### Saving Data

In [184]:
new_copy_orders_dataframe3.to_csv("./orders.csv", index=False)

In [185]:
# Methods [Merge]
df1 = pd.DataFrame()
pd.merge(df_1["price"], df_1["room_type"], on=1, how="inner") # I want to group two serreis to dataframe
pd.DataFrame([df_1["price"], df_1["room_type"]])

NameError: name 'df_1' is not defined