In [4]:
# Introduction
'''
    One of The big Problems in Descion Tree is Overfitting OR underfitting
    Random Forset Solution: this also solve the problem of ....
'''

'\n    One of The big Problems in Descion Tree is Overfitting OR underfitting\n    Random Forset Solution: this also solve the problem of ....\n'

In [12]:
# Import Packages
import pandas as pd
import seaborn as sns

In [13]:
# Get All Dataset Predifined
sns.get_dataset_names()

URLError: <urlopen error [Errno -2] Name or service not known>

In [14]:
healthexp = sns.load_dataset("healthexp")
healthexp.head(3)

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9

In [16]:
# Convert categorical variable into dummy/indicator variables. 
healthexp = pd.get_dummies(healthexp)
healthexp.head(2)

,Year,Spending_USD,Life_Expectancy,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
0,1970,252.311,70.6,False,False,True,False,False,False
1,1970,192.143,72.2,False,True,False,False,False,False

In [21]:
# Get X and y
X = healthexp.drop(["Life_Expectancy"], axis=1)
y = healthexp["Life_Expectancy"]
X.head(2)

,Year,Spending_USD,Country_Canada,Country_France,Country_Germany,Country_Great Britain,Country_Japan,Country_USA
0,1970,252.311,False,False,True,False,False,False
1,1970,192.143,False,True,False,False,False,False

In [50]:
# Split Test Set and Train Set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 
y_test.head(3)

100    77.8
191    80.1
91     77.0
Name: Life_Expectancy, dtype: float64

In [ ]:
# Build Random Forset Model
from sklearn.ensemble import RandomForestRegressor
# Build Model With Set Important Parameter to Avoid Overfitting
rfm = RandomForestRegressor(random_state=0, n_estimators=100, oob_score=True)

In [ ]:
# Fit X and y Train
rfm.fit(X_train, y_train)

RandomForestRegressor(oob_score=True, random_state=0)

In [53]:
# Make Prediction
y_prediction = rfm.predict(X_test)
print("Test Set: ", y_test.to_list())
print("Prediction Set: ", y_prediction)

Test Set:  [77.8, 80.1, 77.0, 79.6, 78.2, 75.2, 77.4, 80.5, 81.8, 79.3, 75.9, 76.2, 81.8, 72.9, 83.9, 76.9, 81.2, 77.9, 72.9, 82.1, 75.9, 75.7, 78.3, 79.4, 78.8, 79.4, 82.0, 82.7, 75.7, 82.7, 80.6, 73.3, 76.8, 81.2, 81.3, 78.9, 78.1, 81.4, 81.3, 74.3, 80.5, 78.2, 84.7, 78.6, 74.7, 76.1, 75.4, 78.8, 79.2, 81.5, 80.5, 74.7, 82.0, 78.2, 78.0]
Prediction Set:  [77.605 80.214 76.841 79.3   78.073 75.182 77.014 80.581 81.749 78.985
 75.59  75.808 81.829 73.207 83.962 76.931 81.131 77.999 72.461 82.291
 75.8   76.326 78.28  79.156 78.49  79.672 81.998 82.61  76.036 82.601
 80.63  73.178 76.547 80.718 80.953 78.77  77.771 81.141 81.216 73.678
 80.316 78.224 84.317 78.669 74.812 76.547 75.171 78.448 78.783 81.519
 80.658 74.558 81.867 77.98  77.597]

In [54]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
print(mean_absolute_error(y_prediction, y_test))
print(root_mean_squared_error(y_prediction, y_test))
print(r2_score(y_prediction, y_test))

0.21316363636362506
0.2641419040109721
0.9912726770467223

#### OOB Error (out-of-bug Error)

In [59]:
print(f"OOB R-squared: {rfm.oob_score_}") # great prediction it close to 1

OOB R-squared: 0.9860599477878613